services:
  - type: web
    name: school-saas
    env: node
    region: ohio
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
